### PR TITLE
Method for creating compressing tree sequence output, adding constrained node ages

### PR DESCRIPTION
**Pull request by nspope**
Hi @leospeidel, 

in case it's useful -- here is a way to dump a compressed tree sequence with equivalent nodes collapsed across marginal trees, with node ages constrained so that branch lengths are positive, and with unconstrained node age stored in node metadata. I used the existing ``include/src/tree_sequence.hpp::DumpTreeSequencesTopoOnly`` with some modifications (a few things needed to be tweaked to generate a valid tree sequence with mutations, etc). The only change to the existing API was to add the ``--compress`` flag to `Convert`.

The workflow looks like,
```bash
# Output compressed tree sequence, with averaged node ages in metadata
$RELATE_LIB/bin/Convert --mode ConvertToTreeSequence \
  --anc $RELATE_LIB/example/example.anc.gz \
  --mut $RELATE_LIB/example/example.mut.gz \
  --compress -o example.compressed.constrained
```

The "constrained node ages" are necessary because just averaging node ages across marginal trees will generally not produce a valid tree sequence (some branch lengths will be negative). So, I find the set of constrained node ages that are closest to the unconstrained node ages, with respect to least squared error. This is done via quadratic programming (w/ an efficient fixed-point algorithm based on the method of alternating projections). On the example data this looks like:

Finally, the hope is that tree shape wouldn't get too screwed up by the constraints. A way to assess this is to dump the uncompressed tree sequences (e.g. all marginal trees with nodes stored separately), and calculate some branch/TMRCA statistics across windows/points in both uncompressed and compressed+constrained output (using tskit). That looks like,

This looks like a reasonable approximation (at least for this example), takes up substantially less space, and should allow quicker stats computations from tskit.

### CODE REVIEW

**Comment by nspope** [comment]
Hi Leo, this should be good to go. Everything is done in C++ now. The strategy is:
1. Use fixed point to get constrained least squares solution, until `--iterations XXX` or convergence tolerance `--tolerance XXX`.
2. This can be slow for huge tree sequences, so once the algorithm terminates, the constraint is forced by biasing node ages backwards in time as necessary (the same strategy is used in tsdate). The least squares optimization can be skipped completely by setting ``--iterations`` to 0. 
3. The unconstrained node ages are stored in the node metadata. These could be accessed via,
```python
import array
import numpy as np
import tskit
ts = tskit.load("my.compressed.trees")
unconstrained_node_times = np.array(array.array('d', ts.tables.nodes.metadata.tobytes()))
# compare with constrained node times, ts.tables.nodes.time
```
On the whole, this strategy seems to work pretty well. Below are constrained vs unconstrained times for a large tree sequence (2940 samples, 523421 trees), for [left] least squares optimized (but terminated after 100 iterations); [right] not optimized (node age biased upwards to force constraint):
<p float="left">
  
   
</p>

In this example, the compressed tree sequence has ~300,000,000 nodes, as opposed to ~1,500,000,000 nodes in the uncompressed tree sequence. The storage footprint is a bit less than the compressed *anc.gz (around ~30 Gb, down from ~40 Gb).

**Comment by hyanwong** [comment]
I think it might be worth using a [schema](https://tskit.dev/tutorials/metadata.html#sec-tutorial-metadata) for the metadata? I'm not sure how you do that in C, however?

**Comment by nspope** [comment]
Good point, thanks @hyanwong. Looks like there's a way to [set it in C](https://tskit.dev/tskit/docs/stable/c-api.html#c.tsk_node_table_set_metadata_schema), guess I could construct in python and copy into the header.

**Comment by hyanwong** [comment]
Ben Jeffery is the metadata guru. He will have some tips, I'm sure. If you can use the [struct](https://tskit.dev/tskit/docs/stable/metadata.html#struct) codec, it will produce a much smaller tree sequence file.

**Comment by hyanwong** [comment]
By the way, this would be *fantastic* to get into Relate, so thanks @nspope. If you want a "quick and dirty" method, you could also just allocate times arbitrarily (e.g. in ascending order as you traverse the graph) and set the tree sequence `time_units` to "uncalibrated". That would only be good for people interested in the topology, of course (although you could later run tsdate on the tree sequence, which we have previously found to give reasonable results).

**Comment by hyanwong** [comment]
By the way, what are you doing with the oldest node in the trees, @nspope ? By the "samples underneath" argument, all the trees will have the same grand MRCA, but this can lead to unwanted behaviour e.g. when re-dating. You may wish to do something similar to the (new) `tsinfer.post_process` routine, and change to new root nodes whenever an edge leading to the root changes in the tree sequence.

**Comment by nspope** [comment]
Ah yes @hyanwong, I used a heuristic to split the grand TMRCA -- set a new root whenever the node IDs of its two children change.

**Comment by hyanwong** [comment]
> Ah yes @hyanwong, I used a heuristic to split the grand TMRCA -- set a new root whenever the node IDs of its two children change. It sounds like this is similar to what tsinfer.post_process is doing?

Great. That's equivalent to what we now do in `tsinfer`, I think (only we don't necessarily have bifurcations, so it's a little more complicated)

**Comment by nspope** [comment]
> you could also just allocate times arbitrarily (e.g. in ascending order as you traverse the graph) and set the tree sequence `time_units` to "uncalibrated".

Makes sense! This is how the tables are originally constructed, so that sorting will get edges in the "right order" for the node age constraint estimation. I'm not sure if there's an advantage to having this as an output option, as opposed to just "brute-forcing" node ages backwards in time until the constraint is satisfied (e.g. disabling the constrained least squares part of the algo). As doing this requires only a single pass over the edge table.

**Comment by hyanwong** [comment]
> The storage footprint is a bit less than the compressed *anc.gz (around ~30 Gb, down from ~40 Gb).

How much of this is due to the metadata? I suspect it might be quite a lot. Look at

```python
md = ts.tables.nodes.metadata
print(md.size * md.itemsize)
```

**Comment by nspope** [comment]
in this case, ~300,000,000 doubles -- so approx 2.5G -- not huge but not trivial. May just be easiest to add a flag to drop the metadata.

**Comment by hyanwong** [comment]
> in this case, ~300,000,000 doubles -- so approx 2.5G -- not huge but not trivial. May just be easiest to add a flag to drop the metadata.

Oh, I see. You are dumping the doubles as raw bytes. I thought you might be JSONing them. So yes, that's as good as you are going to get unless you drop the metadata entirely.

**Comment by hyanwong** [comment]
Also (I though I mentioned this, but can't see it), I wonder if you actually do *better* estimating node time from a (neutrally simulated) genealogy when you do least squares constraining versus inferring independent node times in each tree? That might be a fun thing to test.

**Comment by nspope** [comment]
> I wonder if you actually do _marginally better_ estimating node time from a (neutrally simulated) genealogy when you do least squares constraining versus inferring independent node times in each tree?

Yeah, I was wondering this myself, as there'd be some information sharing across non-neighboring nodes induced by the constraint.

**Comment by nspope** [comment]
One thing that is confusing me is the coordinate system used in Relate vs tskit:
- The SNP positions, tree breaks, etc in Relate are the same as those in the input haplotypes, which follow SHAPEIT2's format and are 1-based (I think?). 
- Whereas tskit has 0-based coordinates (except `TreeSequence.write_vcf` doesn't add an offset of 1 to match the VCF standard, but instead uses the coordinates of each `Site`?)

This may cause sites to be erroneously removed with the following workflow:
1. Use `bedtools` or something to mask a VCF (1-based) with a BED file (0-based)
2. Convert the masked VCF to SHAPEIT2 "haps" format
3. Infer marginal trees using Relate, dump to a tree sequence
4. Delete intervals in tree sequence using intervals from original BED w/ `TreeSequence.delete_intervals`

**Comment by hyanwong** [comment]
I think it would be good to document what this does. Specifically, that it uses exact matching of samples under a node to match between trees, and that it does the ultimate-ancestor-node-splitting thing (identical to step 2 described here: https://tskit.dev/tsinfer/docs/stable/api.html#tsinfer.post_process)

**Comment by nspope** [comment]
I'll add some details to the docstring in a followup, that could be copied over to the blurb in the Relate documentation if it seems necessary.

**Pull request merged**
